name: 'GetParametersByAppName'
description: 'Get all the paraters by Name of the repository'
inputs:
  PROJECT_NAME: 
    description: 'Name of the Project for the App to fecth values from Ssm '
    required: true
    default: 'squint'
  APP_BRANCH_NAME: 
    description: 'Name of the Environment for the App to fecth values from Ssm '
    required: true
    default: 'develop'    
  APPLICATION_NAME: 
    description: 'Name of the Application/Repository for the App to fecth values from Ssm '
    required: true
    default: 'squint-dashboard-tv'  
runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v4
      with:
        repository: teamknowlogy-org/action-get-credentials
        path: my-tools
        ref: main
   
    - run: |
          ls -lrt my-tools
          cd my-tools
          chmod +x getParameters.sh
          ./getParameters.sh "${{ inputs.PROJECT_NAME }}" "${{ inputs.APP_BRANCH_NAME }}" "${{ inputs.APPLICATION_NAME }}"
      shell: bash

