name: 'GetParametersByAppName'
description: 'Get all the parameters by Name of the repository'
inputs:
  PROJECT_NAME: 
    description: 'Name of the Project for the App to fetch values from Ssm '
    required: true
  APPLICATION_NAME: 
    description: 'Name of the Application/Repository for the App to fetch values from Ssm '
    required: true
      
runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v4
      with:
        repository: teamknowlogy-org/action-get-credentials
        path: my-tools
        ref: main
   
    - run: |
          ls -lrt my-tools
          cd my-tools
          chmod +x getParameters.sh
          ./getParameters.sh "${{ inputs.PROJECT_NAME }}" "${{ inputs.APPLICATION_NAME }}"
          wc -l .env
          mv .env ../
      shell: bash

