name: 'GetParametersByAppName'
description: 'Get all the paraters by Name of the repository'
inputs:
  PROJECT_NAME: 
    description: 'Name of the Project for the App to fecth values from Ssm '
    required: true
    default: 'squint'
  APP_BRANCH_NAME: 
    description: 'Name of the Environment for the App to fecth values from Ssm '
    required: true
    default: 'develop'    
  APPLICATION_NAME: 
    description: 'Name of the Application/Repository for the App to fecth values from Ssm '
    required: true
    default: 'squint-dashboard-tv'  
  AWS_ACCESS_KEY_ID:
    description: 'Name of the Project for the App to fecth values from Ssm '
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'Name of the Environment for the App to fecth values from Ssm '
    required: true
  SQUINT_AWS_REGION:
    description: 'Name of the Application/Repository for the App to fecth values from Ssm '
    required: true

env:
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
 SQUINT_AWS_REGION: ${{ secrets.SQUINT_AWS_REGION }}
      
runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v4
      with:
        repository: teamknowlogy-org/action-get-credentials
        path: my-tools
        ref: main
   
    - run: |
          ls -lrt my-tools
          cd my-tools
          chmod +x getParameters.sh
          ./getParameters.sh "${{ inputs.PROJECT_NAME }}" "${{ inputs.APP_BRANCH_NAME }}" "${{ inputs.APPLICATION_NAME }}"
      shell: bash

